<?php

use Illuminate\Database\Seeder;
use App\Models\SysModel\SysObra;

class SysObraTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SysObra::create(["id" =>"1","n_inv" =>"RO 1","id_artista" =>"1","titulo" =>"New York ","tecnica" =>"Óleo sobre tela","dimension" =>"61 x 75,5 cm","ano" =>"1962","edicion" =>"","procedencia" =>"Adquirido a un Argentino","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 1.jpg","file2" =>"RO 1.jpg"]);
        SysObra::create(["id" =>"2","n_inv" =>"RO 2","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"37 x 26 cm","ano" =>"1960","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 2.jpg","file2" =>"RO 2.jpg"]);
        SysObra::create(["id" =>"3","n_inv" =>"RO 3","id_artista" =>"1","titulo" =>"Nocturnal horse","tecnica" =>"Punta seca sobre papel","dimension" =>"38 x 20 cm","ano" =>"1962","edicion" =>"3/10","procedencia" =>"Regalo del artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 3.jpg","file2" =>"RO 3.jpg"]);
        SysObra::create(["id" =>"4","n_inv" =>"RO 4","id_artista" =>"1","titulo" =>"Mr. Peter","tecnica" =>"Punta seca sobre papel","dimension" =>"38 x 20 cm","ano" =>"1961","edicion" =>"7/10","procedencia" =>"Adquirido a un Argentino","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 25","certificacion" =>"","valoracion" =>"","id_ubica" =>"6","file1" =>"RO 4.jpg","file2" =>"RO 4.jpg"]);
        SysObra::create(["id" =>"5","n_inv" =>"RO 5","id_artista" =>"1","titulo" =>"Caballeros","tecnica" =>"Punta seca sobre papel","dimension" =>"18 x 36 cm","ano" =>"1961","edicion" =>"2/8","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 26","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 5.jpg","file2" =>"RO 5.jpg"]);
        SysObra::create(["id" =>"6","n_inv" =>"RO 6","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Mixta sobre papel","dimension" =>"30 x 37 cm","ano" =>"1964","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 6.jpg","file2" =>"RO 6.jpg"]);
        SysObra::create(["id" =>"7","n_inv" =>"RO 7","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Lápiz y grafito sobre papel","dimension" =>"35 x 38 cm","ano" =>"1964","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"8","n_inv" =>"RO 8","id_artista" =>"1","titulo" =>"El ángel caido","tecnica" =>"Punta seca sobre papel","dimension" =>"15,5 x 25,5 cm","ano" =>"1968","edicion" =>"6/10","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 8.jpg","file2" =>"RO 8.jpg"]);
        SysObra::create(["id" =>"9","n_inv" =>"RO 9","id_artista" =>"1","titulo" =>"El hombre nadie","tecnica" =>"Óleo sobre tela","dimension" =>"157 x 147 cm","ano" =>"1968","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 72","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 9.jpg","file2" =>"RO 9.jpg"]);
        SysObra::create(["id" =>"10","n_inv" =>"RO 10","id_artista" =>"1","titulo" =>"La confrontación del alba","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 160 cm","ano" =>"1972","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 80","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 10.jpg","file2" =>"RO 10.jpg"]);
        SysObra::create(["id" =>"11","n_inv" =>"RO 11","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Mixta sobre papel","dimension" =>"35 x 25 cm","ano" =>"1972","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 11.jpg","file2" =>"RO 11.jpg"]);
        SysObra::create(["id" =>"12","n_inv" =>"RO 12","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Óleo sobre tela","dimension" =>"120 x 120 cm","ano" =>"1972","edicion" =>"","procedencia" =>"Casa Remate Segre, Madrid, 2013","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 12.jpg","file2" =>"RO 12.jpg"]);
        SysObra::create(["id" =>"13","n_inv" =>"RO 13","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Óleo sobre tela","dimension" =>"120 x 120 cm","ano" =>"1972","edicion" =>"","procedencia" =>"Casa Remate Segre, Madrid, 2013","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 13.jpg","file2" =>"RO 13.jpg"]);
        SysObra::create(["id" =>"14","n_inv" =>"RO 14","id_artista" =>"1","titulo" =>"La mansión del llanto","tecnica" =>"Óleo sobre tela","dimension" =>"165 x 55 cm","ano" =>"1973","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 14.jpg","file2" =>"RO 14.jpg"]);
        SysObra::create(["id" =>"15","n_inv" =>"RO 15","id_artista" =>"1","titulo" =>"EL lugar donde nacen las divinidades","tecnica" =>"Óleo sobre tela","dimension" =>"99,5 x 79 cm","ano" =>"1977","edicion" =>"","procedencia" =>"Colección Sergio Larraín","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 15.jpg","file2" =>"RO 15.jpg"]);
        SysObra::create(["id" =>"16","n_inv" =>"RO 16","id_artista" =>"1","titulo" =>"Ignis innaturalis","tecnica" =>"Óleo sobre tela","dimension" =>"200 x 160 cm","ano" =>"1979","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 16.jpg","file2" =>"RO 16.jpg"]);
        SysObra::create(["id" =>"17","n_inv" =>"RO 17","id_artista" =>"1","titulo" =>"La aparición del árbol electrico","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 140 cm","ano" =>"1986","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 86","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 17.jpg","file2" =>"RO 17.jpg"]);
        SysObra::create(["id" =>"18","n_inv" =>"RO 18","id_artista" =>"1","titulo" =>"Las notaciones de la infancia","tecnica" =>"Óleo sobre tela","dimension" =>"140 x 130 cm","ano" =>"1986","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.  Pag 98","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 18.jpg","file2" =>"RO 18.jpg"]);
        SysObra::create(["id" =>"19","n_inv" =>"RO 19","id_artista" =>"1","titulo" =>"El Heraldo","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 97 cm","ano" =>"1987","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 101","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 19.jpg","file2" =>"RO 19.jpg"]);
        SysObra::create(["id" =>"20","n_inv" =>"RO 21","id_artista" =>"1","titulo" =>"La barca","tecnica" =>"Óleo sobre tela","dimension" =>"140 x 170 cm","ano" =>"1990","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 105","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 21.jpg","file2" =>"RO 21.jpg"]);
        SysObra::create(["id" =>"21","n_inv" =>"RO 22","id_artista" =>"1","titulo" =>"El amanecer del ermitaño","tecnica" =>"Óleo sobre tela","dimension" =>"150 x 136 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 108","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 22.jpg","file2" =>"RO 22.jpg"]);
        SysObra::create(["id" =>"22","n_inv" =>"RO 23","id_artista" =>"1","titulo" =>"Elogio de la aurora","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 130 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 23.jpg","file2" =>"RO 23.jpg"]);
        SysObra::create(["id" =>"23","n_inv" =>"RO 24","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"20 x 25 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 24.jpg","file2" =>"RO 24.jpg"]);
        SysObra::create(["id" =>"24","n_inv" =>"RO 25","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"20 x 25 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 25.jpg","file2" =>"RO 25.jpg"]);
        SysObra::create(["id" =>"25","n_inv" =>"RO 26","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"26 x 20 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 26.jpg","file2" =>"RO 26.jpg"]);
        SysObra::create(["id" =>"26","n_inv" =>"RO 27","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"69 x 50 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 27.jpg","file2" =>"RO 27.jpg"]);
        SysObra::create(["id" =>"27","n_inv" =>"RO 28","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"72 x 52 cm","ano" =>"1991","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 28.jpg","file2" =>"RO 28.jpg"]);
        SysObra::create(["id" =>"28","n_inv" =>"RO 29","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Óleo sobre tela","dimension" =>"","ano" =>"","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 29.jpg","file2" =>"RO 29.jpg"]);
        SysObra::create(["id" =>"29","n_inv" =>"RO 30","id_artista" =>"1","titulo" =>"El enigma de Galgala","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 100 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 30.jpg","file2" =>"RO 30.jpg"]);
        SysObra::create(["id" =>"30","n_inv" =>"RO 31","id_artista" =>"1","titulo" =>"El soñante","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 130 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 31.jpg","file2" =>"RO 31.jpg"]);
        SysObra::create(["id" =>"31","n_inv" =>"RO 32","id_artista" =>"1","titulo" =>"El sueño de Ariadna","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 100 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 118","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 32.jpg","file2" =>"RO 32.jpg"]);
        SysObra::create(["id" =>"32","n_inv" =>"RO 33","id_artista" =>"1","titulo" =>"En la ribera","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 90 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 127","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 33.jpg","file2" =>"RO 33.jpg"]);
        SysObra::create(["id" =>"33","n_inv" =>"RO 34","id_artista" =>"1","titulo" =>"Encuentro matinal","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 124","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 34.jpg","file2" =>"RO 34.jpg"]);
        SysObra::create(["id" =>"34","n_inv" =>"RO 35","id_artista" =>"1","titulo" =>"La ansiedad","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 130 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 35.jpg","file2" =>"RO 35.jpg"]);
        SysObra::create(["id" =>"35","n_inv" =>"RO 36 ","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 100 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 36 .jpg","file2" =>"RO 36 .jpg"]);
        SysObra::create(["id" =>"36","n_inv" =>"RO 37","id_artista" =>"1","titulo" =>"La diosa de la fertilidad","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 117","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 37.jpg","file2" =>"RO 37.jpg"]);
        SysObra::create(["id" =>"37","n_inv" =>"RO 38","id_artista" =>"1","titulo" =>"La edad sin fin","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 120 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 115","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 38.jpg","file2" =>"RO 38.jpg"]);
        SysObra::create(["id" =>"38","n_inv" =>"RO 40","id_artista" =>"1","titulo" =>"Paisaje sentimental","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 90 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 116","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 40.jpg","file2" =>"RO 40.jpg"]);
        SysObra::create(["id" =>"39","n_inv" =>"RO 41","id_artista" =>"1","titulo" =>"Baño de cristal","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 134","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 41.jpg","file2" =>"RO 41.jpg"]);
        SysObra::create(["id" =>"40","n_inv" =>"RO 42","id_artista" =>"1","titulo" =>"Interior","tecnica" =>"Óleo sobre tela","dimension" =>"160 x135 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 42.jpg","file2" =>"RO 42.jpg"]);
        SysObra::create(["id" =>"41","n_inv" =>"RO 43","id_artista" =>"1","titulo" =>"La taverna","tecnica" =>"Técnica mixta sobre papel","dimension" =>"50 x 69 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 43.jpg","file2" =>"RO 43.jpg"]);
        SysObra::create(["id" =>"42","n_inv" =>"RO 44","id_artista" =>"1","titulo" =>"Venus berg","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 90 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 132","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 44.jpg","file2" =>"RO 44.jpg"]);
        SysObra::create(["id" =>"43","n_inv" =>"RO 45","id_artista" =>"1","titulo" =>"Viento contrario","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 130 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 136","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 45.jpg","file2" =>"RO 45.jpg"]);
        SysObra::create(["id" =>"44","n_inv" =>"RO 46","id_artista" =>"1","titulo" =>"Una visita inesperada","tecnica" =>"Óleo sobre tela","dimension" =>"89,5 x 99 cm","ano" =>"1992","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 46.jpg","file2" =>"RO 46.jpg"]);
        SysObra::create(["id" =>"45","n_inv" =>"RO 47","id_artista" =>"1","titulo" =>"El Resplandeciente","tecnica" =>"Óleo sobre tela","dimension" =>"134 x 159 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte.Pag 137","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 47.jpg","file2" =>"RO 47.jpg"]);
        SysObra::create(["id" =>"46","n_inv" =>"RO 48","id_artista" =>"1","titulo" =>"Detalle de Lesbos","tecnica" =>"Óleo sobre tela","dimension" =>"60 x 70 cm","ano" =>"1993 - 96","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 48.jpg","file2" =>"RO 48.jpg"]);
        SysObra::create(["id" =>"47","n_inv" =>"RO 49","id_artista" =>"1","titulo" =>"El jardin de los monumentos","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. 139 pag","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 49.jpg","file2" =>"RO 49.jpg"]);
        SysObra::create(["id" =>"48","n_inv" =>"RO 50","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"70 x 50 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"5","file1" =>"RO 50.jpg","file2" =>"RO 50.jpg"]);
        SysObra::create(["id" =>"49","n_inv" =>"RO 51","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"70 x 50 cm","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"5","file1" =>"RO 51.jpg","file2" =>"RO 51.jpg"]);
        SysObra::create(["id" =>"50","n_inv" =>"RO 52","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"","dimension" =>"","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 52.jpg","file2" =>"RO 52.jpg"]);
        SysObra::create(["id" =>"51","n_inv" =>"RO 53","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"","dimension" =>"","ano" =>"1993","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 53.jpg","file2" =>"RO 53.jpg"]);
        SysObra::create(["id" =>"52","n_inv" =>"RO 54","id_artista" =>"1","titulo" =>"La ciudad interior","tecnica" =>"Óleo sobre tela","dimension" =>"200 x 300 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 148 - 149","certificacion" =>"","valoracion" =>"","id_ubica" =>"2","file1" =>"RO 54.jpg","file2" =>"RO 54.jpg"]);
        SysObra::create(["id" =>"53","n_inv" =>"RO 55","id_artista" =>"1","titulo" =>"El ocaso","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. 143 pag","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 55.jpg","file2" =>"RO 55.jpg"]);
        SysObra::create(["id" =>"54","n_inv" =>"RO 56","id_artista" =>"1","titulo" =>"Germinación","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 138","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 56.jpg","file2" =>"RO 56.jpg"]);
        SysObra::create(["id" =>"55","n_inv" =>"RO 57","id_artista" =>"1","titulo" =>"Herrero alquimista","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 153","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 57.jpg","file2" =>"RO 57.jpg"]);
        SysObra::create(["id" =>"56","n_inv" =>"RO 58","id_artista" =>"1","titulo" =>"In memoriam ","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 162","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 58.jpg","file2" =>"RO 58.jpg"]);
        SysObra::create(["id" =>"57","n_inv" =>"RO 59","id_artista" =>"1","titulo" =>"La diosa del viento","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 152","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 59.jpg","file2" =>"RO 59.jpg"]);
        SysObra::create(["id" =>"58","n_inv" =>"RO 60","id_artista" =>"1","titulo" =>"La expulsión del paraiso","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 60.jpg","file2" =>"RO 60.jpg"]);
        SysObra::create(["id" =>"59","n_inv" =>"RO 61","id_artista" =>"1","titulo" =>"Los Mundos simulados","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. 142 pag","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 61.jpg","file2" =>"RO 61.jpg"]);
        SysObra::create(["id" =>"60","n_inv" =>"RO 62","id_artista" =>"1","titulo" =>"La frontera","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 100 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 62.jpg","file2" =>"RO 62.jpg"]);
        SysObra::create(["id" =>"61","n_inv" =>"RO 63","id_artista" =>"1","titulo" =>"Retrato invernal","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 63.jpg","file2" =>"RO 63.jpg"]);
        SysObra::create(["id" =>"62","n_inv" =>"RO 64","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Mixta sobre papel","dimension" =>"55 x 70 cm","ano" =>"1994","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 64.jpg","file2" =>"RO 64.jpg"]);
        SysObra::create(["id" =>"63","n_inv" =>"RO 65","id_artista" =>"1","titulo" =>"Actividad minima","tecnica" =>"Óleo sobre tela","dimension" =>"133 x 160 cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 65.jpg","file2" =>"RO 65.jpg"]);
        SysObra::create(["id" =>"64","n_inv" =>"RO 66","id_artista" =>"1","titulo" =>"Despues de la memorio","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 100 cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 189","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 66.jpg","file2" =>"RO 66.jpg"]);
        SysObra::create(["id" =>"65","n_inv" =>"RO 67","id_artista" =>"1","titulo" =>"La nostalgia de Maldoror","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm /135 x 195","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 165","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 67.jpg","file2" =>"RO 67.jpg"]);
        SysObra::create(["id" =>"66","n_inv" =>"RO 68","id_artista" =>"1","titulo" =>"El averno","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 100 cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 176","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 68.jpg","file2" =>"RO 68.jpg"]);
        SysObra::create(["id" =>"67","n_inv" =>"RO 69","id_artista" =>"1","titulo" =>"El encuentro en la triste tempestad","tecnica" =>"Óleo sobre tela","dimension" =>"133,5 x 159 cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 172","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 69.jpg","file2" =>"RO 69.jpg"]);
        SysObra::create(["id" =>"68","n_inv" =>"RO 70","id_artista" =>"1","titulo" =>"La hora previsible","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 73cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 70.jpg","file2" =>"RO 70.jpg"]);
        SysObra::create(["id" =>"69","n_inv" =>"RO 71","id_artista" =>"1","titulo" =>"La huida","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 135 cm","ano" =>"1995","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 165","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 71.jpg","file2" =>"RO 71.jpg"]);
        SysObra::create(["id" =>"70","n_inv" =>"RO 72","id_artista" =>"1","titulo" =>"Amatemineuriv","tecnica" =>"Técnica mixta sobre papel","dimension" =>"147 x 144 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 72.jpg","file2" =>"RO 72.jpg"]);
        SysObra::create(["id" =>"71","n_inv" =>"RO 73","id_artista" =>"1","titulo" =>"Cotidiano","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 130 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 73.jpg","file2" =>"RO 73.jpg"]);
        SysObra::create(["id" =>"72","n_inv" =>"RO 74","id_artista" =>"1","titulo" =>"El bosque ausente","tecnica" =>"Óleo sobre tela","dimension" =>"135 x 160 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 165","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 74.jpg","file2" =>"RO 74.jpg"]);
        SysObra::create(["id" =>"73","n_inv" =>"RO 75","id_artista" =>"1","titulo" =>"El simulacro","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 100 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 75.jpg","file2" =>"RO 75.jpg"]);
        SysObra::create(["id" =>"74","n_inv" =>"RO 76","id_artista" =>"1","titulo" =>"Insectario","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 100 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 76.jpg","file2" =>"RO 76.jpg"]);
        SysObra::create(["id" =>"75","n_inv" =>"RO 77","id_artista" =>"1","titulo" =>"Interior","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 70 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 77.jpg","file2" =>"RO 77.jpg"]);
        SysObra::create(["id" =>"76","n_inv" =>"RO 78","id_artista" =>"1","titulo" =>"El interior","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 130 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 78.jpg","file2" =>"RO 78.jpg"]);
        SysObra::create(["id" =>"77","n_inv" =>"RO 79","id_artista" =>"1","titulo" =>"La resurección","tecnica" =>"Óleo sobre tela","dimension" =>"165 x 132cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"Advis, Luis; Couve, Adolfo; Galaz, Gaspar;Ivelic, Milan; Quintana, Sonia, Opazo. Rodolfo Opazo. Pinturas 1958 - 1996, 1996, Tomás Andreu Galeria de Arte. Pag 206","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 79.jpg","file2" =>"RO 79.jpg"]);
        SysObra::create(["id" =>"78","n_inv" =>"RO 80","id_artista" =>"1","titulo" =>"La cascada","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 110 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 80.jpg","file2" =>"RO 80.jpg"]);
        SysObra::create(["id" =>"79","n_inv" =>"RO 81","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"","ano" =>"","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 81.jpg","file2" =>"RO 81.jpg"]);
        SysObra::create(["id" =>"80","n_inv" =>"RO 82","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"","ano" =>"","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 82.jpg","file2" =>"RO 82.jpg"]);
        SysObra::create(["id" =>"81","n_inv" =>"RO 83","id_artista" =>"1","titulo" =>"Marina","tecnica" =>"Óleo sobre tela","dimension" =>"70 x 100 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 83.jpg","file2" =>"RO 83.jpg"]);
        SysObra::create(["id" =>"82","n_inv" =>"RO 84","id_artista" =>"1","titulo" =>"Matinal","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 90 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 84.jpg","file2" =>"RO 84.jpg"]);
        SysObra::create(["id" =>"83","n_inv" =>"RO 85","id_artista" =>"1","titulo" =>"Paisaje ","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 110 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 85.jpg","file2" =>"RO 85.jpg"]);
        SysObra::create(["id" =>"84","n_inv" =>"RO 86","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Mixta sobre papel","dimension" =>"68 x 48 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 86.jpg","file2" =>"RO 86.jpg"]);
        SysObra::create(["id" =>"85","n_inv" =>"RO 87","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Mixta sobre papel","dimension" =>"68 x 48 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 87.jpg","file2" =>"RO 87.jpg"]);
        SysObra::create(["id" =>"86","n_inv" =>"RO 88","id_artista" =>"1","titulo" =>"La rafaga","tecnica" =>"Óleo sobre tela","dimension" =>"110 x 130 cm","ano" =>"1996","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 88.jpg","file2" =>"RO 88.jpg"]);
        SysObra::create(["id" =>"87","n_inv" =>"RO 89","id_artista" =>"1","titulo" =>"Cariatide","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 120 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 89.jpg","file2" =>"RO 89.jpg"]);
        SysObra::create(["id" =>"88","n_inv" =>"RO 90","id_artista" =>"1","titulo" =>"El arrebato 1","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 70 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 90.jpg","file2" =>"RO 90.jpg"]);
        SysObra::create(["id" =>"89","n_inv" =>"RO 91","id_artista" =>"1","titulo" =>"El arrebato 2","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 70 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 91.jpg","file2" =>"RO 91.jpg"]);
        SysObra::create(["id" =>"90","n_inv" =>"RO 92","id_artista" =>"1","titulo" =>"Evación","tecnica" =>"Óleo sobre tela","dimension" =>"90 x 100 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 92.jpg","file2" =>"RO 92.jpg"]);
        SysObra::create(["id" =>"91","n_inv" =>"RO 93","id_artista" =>"1","titulo" =>"La casa de Asterion","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 180 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 93.jpg","file2" =>"RO 93.jpg"]);
        SysObra::create(["id" =>"92","n_inv" =>"RO 94","id_artista" =>"1","titulo" =>"Laguna estigia","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 180 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 94.jpg","file2" =>"RO 94.jpg"]);
        SysObra::create(["id" =>"93","n_inv" =>"RO 95","id_artista" =>"1","titulo" =>"Naturaleza muerta","tecnica" =>"Óleo sobre tela","dimension" =>"70 x 100 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 95.jpg","file2" =>"RO 95.jpg"]);
        SysObra::create(["id" =>"94","n_inv" =>"RO 96","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"48 x 68 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 96.jpg","file2" =>"RO 96.jpg"]);
        SysObra::create(["id" =>"95","n_inv" =>"RO 97","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"48 x 68 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 97.jpg","file2" =>"RO 97.jpg"]);
        SysObra::create(["id" =>"96","n_inv" =>"RO 98","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"50 x 66 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 98.jpg","file2" =>"RO 98.jpg"]);
        SysObra::create(["id" =>"97","n_inv" =>"RO 99","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"50 x 70 cm","ano" =>"1997","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 99.jpg","file2" =>"RO 99.jpg"]);
        SysObra::create(["id" =>"98","n_inv" =>"RO 100","id_artista" =>"1","titulo" =>"Sin Titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"72 x 105 xm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 100.jpg","file2" =>"RO 100.jpg"]);
        SysObra::create(["id" =>"99","n_inv" =>"RO 101","id_artista" =>"1","titulo" =>"Alerta de lo inmovil","tecnica" =>"Óleo sobre tela","dimension" =>"80 x 110 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 101.jpg","file2" =>"RO 101.jpg"]);
        SysObra::create(["id" =>"100","n_inv" =>"RO 102","id_artista" =>"1","titulo" =>"Cielo abierto","tecnica" =>"Óleo sobre tela","dimension" =>"100 x 80 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 102.jpg","file2" =>"RO 102.jpg"]);
        SysObra::create(["id" =>"101","n_inv" =>"RO 103","id_artista" =>"1","titulo" =>"El impulso","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 110 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 103.jpg","file2" =>"RO 103.jpg"]);
        SysObra::create(["id" =>"102","n_inv" =>"RO 104","id_artista" =>"1","titulo" =>"La terraza de las audiencias","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 160 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 104.jpg","file2" =>"RO 104.jpg"]);
        SysObra::create(["id" =>"103","n_inv" =>"RO 105","id_artista" =>"1","titulo" =>"Movimiento recordatorio","tecnica" =>"Óleo sobre tela","dimension" =>"70 x 90 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 105.jpg","file2" =>"RO 105.jpg"]);
        SysObra::create(["id" =>"104","n_inv" =>"RO 106","id_artista" =>"1","titulo" =>"nube sin presagio","tecnica" =>"Óleo sobre tela","dimension" =>"81 x 100 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 106.jpg","file2" =>"RO 106.jpg"]);
        SysObra::create(["id" =>"105","n_inv" =>"RO 107","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Técnica mixta sobre papel","dimension" =>"48 x 68 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 107.jpg","file2" =>"RO 107.jpg"]);
        SysObra::create(["id" =>"106","n_inv" =>"RO 108","id_artista" =>"1","titulo" =>"Sin titulo","tecnica" =>"Óleo sobre tela","dimension" =>"150 x 150 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 108.jpg","file2" =>"RO 108.jpg"]);
        SysObra::create(["id" =>"107","n_inv" =>"RO 109","id_artista" =>"1","titulo" =>"Matinal","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 200 cm","ano" =>"1998","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"7","file1" =>"RO 109.jpg","file2" =>"RO 109.jpg"]);
        SysObra::create(["id" =>"108","n_inv" =>"RO 110","id_artista" =>"1","titulo" =>"Elejia","tecnica" =>"Mixta sobre papel","dimension" =>"50 x 69 cm","ano" =>"1999","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 110.jpg","file2" =>"RO 110.jpg"]);
        SysObra::create(["id" =>"109","n_inv" =>"RO 111","id_artista" =>"1","titulo" =>"El signo de los tiempos","tecnica" =>"Óleo sobre tela","dimension" =>"160 x 130 cm","ano" =>"1999","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 111.jpg","file2" =>"RO 111.jpg"]);
        SysObra::create(["id" =>"110","n_inv" =>"RO 112","id_artista" =>"1","titulo" =>"El altar del sueño","tecnica" =>"Óleo sobre tela","dimension" =>"130 x 160 cm","ano" =>"1999","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 112.jpg","file2" =>"RO 112.jpg"]);
        SysObra::create(["id" =>"111","n_inv" =>"RO 113","id_artista" =>"1","titulo" =>"In - mundo","tecnica" =>"Mixta sobre papel","dimension" =>"50 x 69 cm","ano" =>"1999","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"RO 113.jpg","file2" =>"RO 113.jpg"]);
        SysObra::create(["id" =>"112","n_inv" =>"RO 114","id_artista" =>"1","titulo" =>"In- Paraiso","tecnica" =>"Mixta sobre papel","dimension" =>"57 x 74 cm","ano" =>"2000","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 114.jpg","file2" =>"RO 114.jpg"]);
        SysObra::create(["id" =>"113","n_inv" =>"RO 20","id_artista" =>"1","titulo" =>"Cuestion de tiempo","tecnica" =>"Mixta sobre papel","dimension" =>"68 x 48 cm","ano" =>"2000","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 20.jpg","file2" =>"RO 20.jpg"]);
        SysObra::create(["id" =>"114","n_inv" =>"RO 39","id_artista" =>"1","titulo" =>"Actividad infima","tecnica" =>"Mixta sobre papel","dimension" =>"55 x 56 cm","ano" =>"2000","edicion" =>"","procedencia" =>"Adquirido directamente al artista Rodolfo Opazo","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"RO 39.jpg","file2" =>"RO 39.jpg"]);

        SysObra::create(["id" =>"115","n_inv" =>"CP 1","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"13 x 13 cm","ano" =>"","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"9","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"116","n_inv" =>"CP 2","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"Óleo sobre tela","dimension" =>"120 x 92 cm","ano" =>"1965","edicion" =>"","procedencia" =>"Eduardo Lira","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"117","n_inv" =>"CP 3","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"Óleo sobre tela","dimension" =>"120 x 61,5 cm o 124 x 64 cm","ano" =>"1973","edicion" =>"","procedencia" =>"Pablo Urzua","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"CP 3.jpg","file2" =>"CP 3.jpg"]);
        SysObra::create(["id" =>"118","n_inv" =>"CP 4","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"39 x 29 cm","ano" =>"1975","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"10","file1" =>"CP 4.jpg","file2" =>"CP 4.jpg"]);
        SysObra::create(["id" =>"119","n_inv" =>"CP 5","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"39 x 29 cm","ano" =>"1975","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"10","file1" =>"CP 5.jpg","file2" =>"CP 5.jpg"]);
        SysObra::create(["id" =>"120","n_inv" =>"CP 6","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"15 x 13 cm","ano" =>"","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"9","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"121","n_inv" =>"CP 7","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"15 x 13 cm","ano" =>"","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"9","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"122","n_inv" =>"CP 8","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"14 x 14 cm","ano" =>"","edicion" =>"","procedencia" =>"Directamente a la Artista Carmen Piemonte","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"9","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"123","n_inv" =>"CP 9","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"","dimension" =>"120 x 90 cm","ano" =>"","edicion" =>"","procedencia" =>"Eduardo Lira","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"1000","file1" =>"","file2" =>""]);
        SysObra::create(["id" =>"124","n_inv" =>"CP 10","id_artista" =>"2","titulo" =>"Sin titulo","tecnica" =>"Óleo sobre tela ","dimension" =>"72,7  x 53,7 cm","ano" =>"1972","edicion" =>"","procedencia" =>"Ramón Sotomayor","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"8","file1" =>"CP 10.jpg","file2" =>"CP 10.jpg"]);

        SysObra::create(["id" =>"125","n_inv" =>"MV 1","id_artista" =>"3","titulo" =>"Sin titulo","tecnica" =>"madera tallada","dimension" =>"180 x 34 x 29 cm","ano" =>"","edicion" =>"","procedencia" =>"Galería Artium","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"11","file1" =>"MV 1.jpg","file2" =>"MV 1.jpg"]);
        SysObra::create(["id" =>"126","n_inv" =>"MV 2","id_artista" =>"3","titulo" =>"Sin titulo","tecnica" =>"Bronce","dimension" =>"78,3 x 73 x 23 cm","ano" =>"","edicion" =>"","procedencia" =>"Directamente al artista Matías Vial","catalogo" =>"","certificacion" =>"","valoracion" =>"","id_ubica" =>"2","file1" =>"","file2" =>""]);
    }
}
